name: Pull Request Workflow
on:
  pull_request:
    branches:
      - master
jobs:
    lint-and-test:
        runs-on: ubuntu-lastest


        steps:
        -  name: check out code
           uses: actions/checkout@v3

        -  name: Run linter
           run: |
            echo "Running linter"
            echo "Linting complete"
        -  name: run tests
           run: |
            echo "Running tests"
            echo "Tests complete"
